config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_period_associations
  resources :event_job_job_associations
  resources :events
  resources :periods
  resources :jobs
  resources :users
  resources :microposts,          only: [:create, :destroy]

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'
  post "periods/change", as: :change_periods
  post "periods/destroy_all", as: :destroy_all_periods
  post   'login'   => 'sessions#create'
  post   'logout'   => 'sessions#destroy'

  get 'sessions/new'
  get 'users/new'
  get 'home'       => 'static_pages#home'
  get 'offer'       => 'static_pages#offer'
  get 'impression'       => 'static_pages#impression'
  get 'impressum'  => 'static_pages#impressum'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'signup'     => 'users#new'
  get  'login'   => 'sessions#new'

  root 'static_pages#home'

  delete 'logout'  => 'sessions#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def impression
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
      @microposts = Micropost.all
  end

  def about
  end

  def offer
  end

  def impressum
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Über uns") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>

<h1>Über die Gründer</h1>
<br>
<div style="text-align:right">
  <div class="image">
    <div style=><%=image_tag("Xelat.jpg", width: "140", height: "200")%></div>
    <p> Xelat Akcam</p>
  </div>

  <div class="image">
    <div style=><%=image_tag("Hayat.jpg", width: "140", height: "200")%></div>
    <p> Hayat Boulakhrif </p>
  </div>

  <div class="image">
    <div style=><%=image_tag("Nadia.jpg", width: "150", height: "200")%></div>
    <p> Nadia Kruszewski </p>
  </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<p>Wir sind die drei Gründerinnen der EvenTraum GmbH.
  Nach erfolgreichem Abschluss Bachelor of Science der Wirtschaftswissenschaft an der Gottfried Wilhelm Leibniz Universität Hannover studieren wir nun gemeinsam den Master of Sciecne im Major Operations Management and Research.... </p>
<br>
<h1>Über das Unternehmen</h1>
<p>Im Rahmen der Veranstaltung „Entwicklung von Anwendungssystemen“
  am <a href="http://www.prod.uni-hannover.de">Institut für Produktionswirtschaft</a> im Master „Operations Management and Research“
  an der Gottfried Wilhelm Leibniz Universität Hannover ist die Web-Applikation „EvenTraum“ entwickelt worden.<br>
  Die Web-Applikation basiert auf dem <a href="http://3rd-edition.railstutorial.org/">Ruby on Rails Tutorial – Learn Web Development with Rails</a> von Michael Hartl.<br>
  Mit der Web-Applikation „EvenTraum“ kann ein Multi-Projekt-Planungsproblem gelöst werden.
</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Kontakt") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>Kontakt</h1>
<br>
<p>Kontaktieren Sie bei Rückfragen oder Anregungen gerne das EvenTraum-Team.
  <br><br>
  <%= mail_to ("xelat.akcam@gmail.com"), "Xelat Akcam", :style=> "font-weight: bold" %>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  xelat.akcam@gmail.com" %></div>
<br><br>
<%= mail_to ("ha.boulakhrif@web.de"), "Hayat Boulakhrif", :style=> "font-weight: bold" %><br><br>
<div style=""><%=image_tag("email.png", size: "25") + "  ha.boulakhrif@web.de" %></div>
<br><br>
<%= mail_to ("nadia.kruszewski@yahoo.de"), "Nadia Kruszewski", :style=> "font-weight: bold" %><br><br>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  nadia.kruszewski@yahoo.de" %></div>
</p>
</body>
</html>


app/views/static_pages/home.html.erb
<% provide(:title, "EvenTraum") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<ul class="bxslider">
  <div style="text-align:center"><%=image_tag("Image_0.png") %></div>
  <div style="text-align:center"><%=image_tag("Image_1.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_3.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_5.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_6.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_7.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_8.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_9.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_10.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_12.jpg") %></div>
</ul>
</html>

app/views/static_pages/impression.html.erb
<% provide(:title, "Impressionen") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<div class="span8">
  <ul class="microposts">
    <% @microposts.each do |micropost| %>
        <li>
          <ol class="microposts">
            <%= render @microposts %>
          </ol>
        </li>
    <% end %>
    </ul>
  </div>
</body>

</html>

app/views/static_pages/impressum.html.erb
<% provide(:title, "Impressum") %>
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %> | EvenTraum</title>
  </head>
  <body>

  <h1>Impressum</h1>

  <p>
    EvenTraum GmbH<br>
    c/o Leibniz Universität Hannover<br>
    Institut für Produktionswirtschaft<br>
    Königsworther Platz 1<br>
    D-30167 Hannover<br>
    Email: eventraum@gmail.com<br><br>
    Vertretungsberichtsberechtigter Vorstand:<br>
    Xelat Akcam<br>
    Hayat Boulakhrif<br>
    Nadia Kruszewski
  </p>

  </body>

</html>

app/views/static_pages/offer.html.erb
<% provide(:title, "Angebot") %>
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>EvenTraum realisiert das Event Ihrer Träume</h1>
<br>
<p>Entscheiden Sie selbst, was zu Ihrem persönlichen EvenTraum dazu gehört:
  Ob Catering, Entertainment oder die passende Raumdekoration, wir kümmern uns für Sie um all Ihre Wünsche.
  Mit viel Engagement, Liebe zum Detail und geschultes Personal bieten wir einen rundum Service der besonderen Art an.
  Unser Ziel besteht darin, einzigartige und unvergessliche Erlebnismomente für Sie und Ihre Gäste zu erschaffen.
  Es ist unser Herzensanliegen Ihnen ein  perfektes Event zu organisieren.</p>
</body>
<body>
<div class="info">
  <div style==><%=image_tag("Image_8.jpg", width: "500", height:  "300") %></div>
  <p>Unser Depot an Räumen erlaubt es uns jegliche Art von Veranstaltungen zu organisieren. Sei es die Hochzeit, Geburtstage, Firmenevents, etc.. Ebenfalls wird für die dem Anlass entsprechende Dekorationen der Räume gesorgt, teilen Sie uns Ihre Wünsche mit.
    Ihre Träume sind keine Grenzen gesetzt</p>
</div>
<br><br><br><br><br><br><br><br><br><br><br>
</body>
<body>
<div class="info">
    <div style=><%=image_tag("Image_3.jpg", width: "500", height: "300")%></div>
    <p> Wir bieten im Bereich des Catering variantenreiche Küchen an, die sich über die orientalische, kulinarische, spanische, italienische und deutsche Küche erstreckt. Unser vielfältiges Angebot kann sowohl als Buffet  als auch als Menü serviert werden.
    </p>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
</body>
<body>
  <div class="info">
    <div style=><%=image_tag("Image_10.jpg", width: "500", height: "300")%></div>
    <p>  Im Bereich des Entertainment bieten wir Life Musik, Orchester und DJs an.</p>
  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br>
</body>
<br><br><br><br>
<p>Fordern Sie uns heraus –wir  freuen uns auf Sie!</p>

</html>

app/views/static_pages/tcpsp.html.erb
<% provide(:title, 'Optimierung') %>
<h1>Multi-Projektplannung mit dem TCPSP</h1>
<p>
  Auf dieser Seite startet die Losgrößenplanung!    <br>     <br>

  <%= link_to "Hier geht es zur Verwaltung der Events!", events_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Vorgänge!", jobs_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Event-Vorgänger-Nachfolger!", event_job_job_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Perioden!", periods_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Event-Vorgang-Periode!", event_job_period_associations_path %><br>
</p>

<br>

<% if logged_in? %>


      <div class="image">
      <%= link_to image_tag("gams.jpg", height: '50', alt:"GAMS logo"), gams_paths_path %><br>
      <%= link_to 'Verwaltung des GAMS-Pfads', gams_paths_path %> <br>
      </div>


    <%= button_to "Lösche den Produktions- und Lagerplan", :controller => 'event_job_period_associations', :action => 'delete_old_plan' %>
    <%= button_to "Optimiere", :controller => 'event_job_period_associations', :action => 'optimize' %>
    <%= button_to "Zeigen", :controller => 'event_job_period_associations', :action => 'read_optimization_results' %>

    <% if @objective_function_value!=nil %>
        Die Kosten betragen <%=   @objective_function_value %> Geldeinheiten!   <br>   <br>
    <% end %>
<% end %>