config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_period_associations
  resources :event_job_job_associations
  resources :events
  resources :periods
  resources :jobs
  resources :users
  resources :microposts,          only: [:create, :destroy]

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'
  post "periods/change", as: :change_periods
  post "periods/destroy_all", as: :destroy_all_periods
  post   'login'   => 'sessions#create'
  post   'logout'   => 'sessions#destroy'

  get 'sessions/new'
  get 'users/new'
  get 'home'       => 'static_pages#home'
  get 'offer'       => 'static_pages#offer'
  get 'impression'       => 'static_pages#impression'
  get 'impressum'  => 'static_pages#impressum'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'signup'     => 'users#new'
  get  'login'   => 'sessions#new'

  root 'static_pages#home'

  delete 'logout'  => 'sessions#destroy'

end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :events, through: :event_job_period_associations
  has_many :jobs, through: :event_job_period_associations
  has_many :event_job_period_associations, dependent: :destroy
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
      @periods = Period.all
      @number_of_periods = Period.count
      @sum_add_cappa=Period.sum('add_cappa')
      if @mynumber_of_periods = nil
        @mynumber_of_periods=@number_of_periods
      end

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @periods }
      end
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Die Periode wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end




  def change
    @mynumber_of_periods = params[:mynewnumber].to_i
    @number_of_periods = Period.count
    (0..@number_of_periods-1).each do |number|
      name="t#{number}"
      Period.find_by_name(name).destroy
    end
    @events = Event.all
    @jobs = Job.all
    (0..@mynumber_of_periods).each do |number|
      name="t#{number}" and
          date=Time.now+number.days
      @new_period=Period.create!(name: name, time: date)
      @jobs.each{ |jo|
        EventJobPeriodAssociation.create(event_id: jo.event.id, job_id: jo.id, period_id: @new_period.id)
      }
    end
    @periods = Period.all
    redirect_to :action => :index
  end


  def destroy_all
    @periods=Period.all
    @periods.each {|number|
      Period.find(number).destroy}

    @periods = Period.all
    redirect_to :action => :index and return
  end
    # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Die Periode wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Die Periode wurde entfernt.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:name, :time, :add_cappa)
    end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label 'Perioden anlegen' %><br>
      <%= f.text_field :name, type: "number", min:0, required:"required" %>
    </div>
    <div class="field">
      <%= f.label 'Zusatzkapazität anlegen' %><br>
      <%= f.number_field :add_cappa, type: "number", min:1, required:"required" %>
    </div>
    <div class="actions">
      <%= f.submit 'Perioden anlegen oder aktualisieren' %>
    </div>
<% end %>

app/views/periods/edit.html.erb
<h1>Perioden aktualisieren</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @period %> |
<%= link_to 'Zurück', periods_path %>

app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Übersicht der Perioden</h1>

<table id="periods" class="display">
  <thead>
    <tr>
      <th>Periode</th>
      <th>Datum</th>
      <th>Zusatzkapazität</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= period.name %></td>
        <td><%= period.time %></td>
        <td><%= period.add_cappa %></td>
        <td><%= link_to 'Anzeigen', period %></td>
        <td><%= link_to 'Ändern', edit_period_path(period) %></td>
        <td><%= link_to 'Entfernen', period, method: :delete, data: { confirm: 'Möchten Sie diesen Eintrag sicher löschen?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <b>Anzahl der Zusatzkapazitäten:</b>
  <%= @sum_add_cappa %> Hilfskräfte
</p>

<p>
  <b>Anzahl der Perioden:</b>
  <%= @number_of_periods %> Perioden
</p>


<%= form_tag change_periods_path %>
<div class="field">
  <%= label_tag :mynewnumber, "Tragen Sie hier bitte die gewünschte Anzahl von Perioden ein:" %>
  <%= text_field_tag :mynewnumber, @mynumber_of_periods  %>
</div>
<%= submit_tag "Anzahl der Perioden anpassen" %>



<%= link_to 'Neue Periode', new_period_path %>
<br>  <br><%= link_to 'Zurück zur Eventplanung', tcpsp_path %>

app/views/periods/new.html.erb
<h1>Neue Periode</h1>

<%= render 'form' %>

<%= link_to 'Zurück', periods_path %>

app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @period, :name %>
</p>

<p>
  <strong>Datum:</strong>
  <%= best_in_place @period, :time %>
</p>

<%= link_to 'Ändern', edit_period_path(@period) %> |
<%= link_to 'Zurück', periods_path %>